### ISSUE TITLE
TargetInvocationException when trying to define OnScreenSize from ContentPage.Resources

### ISSUE THREAD

**Issue by nathenxbrewer** [carolzbnbr/OnScreenSizeMarkup.Maui#5]
**Describe the bug**
The in-line XAML extension is working great but I want to be able to define a FontSize in my Resources for reusability. I followed the example but I'm getting a TargetInvocationException every time I try to reference the key as a StaticResource. 

Testing on Android, using a Pixel 6a. 

` <ContentPage.Resources>
        <maui:OnScreenSize x:Key="BodyFontSize" Default="20" ExtraSmall="16" Small="18" />
    </ContentPage.Resources>`

` <Label Grid.Row="1" HorizontalTextAlignment="Center" FontSize="{StaticResource BodyFontSize}">`

Full Exception: 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Microsoft.Maui.Controls.ResourceDictionary'.
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.ProvideValue(Object& value, ElementNode node, Object source, XmlName propertyName) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 295
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 119
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 189
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 240
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 212
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[AutoPowerPage](AutoPowerPage view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\ViewExtensions.cs:line 37
   at KlipschConnect.Pages.Onboarding.AutoPowerPage.InitializeComponent() in /Users/nathenbrewer/Documents/GitHub/App-Klipsch-Connect-XP/Klipsch Connect XP/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Pages_Onboarding_AutoPowerPage.xaml.sg.cs:line 22
   at KlipschConnect.Pages.Onboarding.AutoPowerPage..ctor() in /Users/nathenbrewer/Documents/GitHub/App-Klipsch-Connect-XP/Klipsch Connect XP/Pages/Onboarding/AutoPowerPage.xaml.cs:line 12
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.Routing.TypeRouteFactory.GetOrCreate(IServiceProvider services) in D:\a\_work\1\s\src\Controls\src\Core\Routing.cs:line 280
   at Microsoft.Maui.Controls.Routing.GetOrCreateContent(String route, IServiceProvider services) in D:\a\_work\1\s\src\Controls\src\Core\Routing.cs:line 169
   at Microsoft.Maui.Controls.ShellSection.GetOrCreateFromRoute(String route, ShellRouteParameters queryData, IServiceProvider services, Boolean isLast, Boolean isPopping) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 485
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 526
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 196
   at KlipschConnect.Pages.Onboarding.EQInfoPage.Continue_Clicked(Object sender, EventArgs e) in /Users/nathenbrewer/Documents/GitHub/App-Klipsch-Connect-XP/Klipsch Connect XP/Pages/Onboarding/EQInfoPage.xaml.cs:line 29
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

**Comment by carolzbnbr** [comment]
Hi @nathenxbrewer,

It seems you are missing specifying the *fallbackType*:

Try this:
```xml
        <OnPlatform x:Key="LargeFontSize" x:TypeArguments="x:Double">
            <OnPlatform.Platforms>
                <On Platform="Android">
                    <markups:OnScreenSize FallbackType="{x:Type x:Double}"  Default="15" Small="16" Medium="17" Large="19"   />
                </On>
                <On Platform="iOS">
                    <markups:OnScreenSize FallbackType="{x:Type x:Double}"   Default="15"  Medium="17" Large="19"    />
                </On>
            </OnPlatform.Platforms>
        </OnPlatform>
```

**Comment by nathenxbrewer** [comment]
`    <maui:OnScreenSize x:Key="LargeFontSize" FallbackType="{x:Type x:Double}"  Base="50" ExtraSmall="0.75"/>
`

Produces the same error. I do not need to specify the platform. To clarify, I am doing this from within a Styles.xaml file within a ResourceDictionary.

**Comment by nathenxbrewer** [comment]
```Xaml
    <maui:OnScreenSize x:Key="LargeFontSize" FallbackType="{x:Type x:Double}"  Default="20" ExtraSmall="16"/>
```

This works though.

**Comment by carolzbnbr** [comment]
Thats odd...

Could you share a sample project so I can try to reproduce the error on my end?

**Comment by carolzbnbr** [comment]
try this
```xml
    <maui:OnScreenSize x:Key="LargeFontSize" FallbackType="{x:Type x:Double}"  Base="50" Default="1" ExtraSmall="0.75"/>
```
So in this case, as we are setting default=1 we are telling the markup to assume as the default size the value of *Base* which is 50. and for ExtraSmall screen categories, it will reduze (multiple) to 0.75 of 50, which is 37

**Comment by carolzbnbr** [comment]
If my previous suggestion doesn't work, please send a sample project so I can try to reproduce the issue here.

**Comment by nathenxbrewer** [comment]
> ```
> ```
>     <maui:OnScreenSize x:Key="LargeFontSize" FallbackType="{x:Type x:Double}"  Base="50" Default="1" ExtraSmall="0.75"/>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

This worked. Looks like adding Default was what did it. Thanks!
